version: '3'

services:
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/www
      - ./.docker/nginx/certs:/etc/nginx/certs
    links:
      - php
    networks:
      - internal

  php:
    build: ./.docker/php
    container_name: php8
    volumes:
      - .:/www
    networks:
      - internal

networks:
  internal:
    driver: bridge
